"""K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUE5efD3tlzBk4VC1bLr3rbQFzyofRKx
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Leer el archivo
df = pd.read_csv("dataset_clientes.csv")

# Variables para el clustering
X = df[[
    "Compras_Mensuales",
    "Gasto_Mensual_MXN",
    "Dias_Desde_Ultima_Compra"
]]

# Eliminar nulos
X = X.dropna()

# Escalar datos
escalador = StandardScaler()
X_escalado = escalador.fit_transform(X)

# Modelo K-Means
modelo = KMeans(n_clusters=3, random_state=42, n_init=10)

# Entrenar
clusters = modelo.fit_predict(X_escalado)

# Agregar el clúster
df_limpio = X.copy()
df_limpio["Cluster"] = clusters

# Resultados
print(df_limpio)

print("\nPromedio por clúster:")
print(df_limpio.groupby("Cluster").mean())
#Interpretación:
#El algoritmo K-Means agrupó a los clientes en tres clústeres con características similares, considerando las
#variables compras mensuales, gasto mensual y días desde la última compra. Los resultados muestran que cada grupo
#presenta un comportamiento de compra diferente, lo que permite identificar
#segmentos de clientes para diseñar estrategias específicas de marketing, promociones y fidelización.

import pandas as pd
import os

datos = {
    "Compras_Mensuales": [2, 3, 5, 8, 10, 12, 15, 18, 20, 22],
    "Gasto_Mensual_MXN": [500, 700, 900, 1500, 1800, 2200, 2800, 3200, 3500, 4000],
    "Dias_Desde_Ultima_Compra": [60, 55, 50, 40, 35, 30, 25, 20, 15, 10]
}

df = pd.DataFrame(datos)

file_name = "dataset_clientes.csv"
df.to_csv(file_name, index=False)

if os.path.exists(file_name):
    print(f"Archivo '{file_name}' creado correctamente y verificado.")
else:
    print(f"Error: El archivo '{file_name}' no pudo ser creado o no se encuentra.")
