# -*- coding: utf-8 -*-
"""Red neuronal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7I0oJcRQIeBIdbg2gXy66nmAPqRnli3
"""

#Practica 2

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("clientes (1).csv")
print("Primeras filas del dataset:")
print(df.head())
#print("\nInformación del dataset:")
#print(df.info())

X = df[[
    "Compras_Mensuales",
    "Gasto_Mensual_MXN",
    "Visitas_Web_Mensuales",
    "Satisfaccion"
]]

y = df["Nivel_Consumo_Referencia"]


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

escalador = StandardScaler()

X_train_escalado = escalador.fit_transform(X_train)
X_test_escalado = escalador.transform(X_test)

modelo = MLPClassifier(
    hidden_layer_sizes=(8, 6),
    activation="relu",
    max_iter=1000,
    random_state=42
)

modelo.fit(X_train_escalado, y_train)

predicciones = modelo.predict(X_test_escalado)

exactitud = accuracy_score(y_test, predicciones)

print("\nExactitud del modelo:")
print(exactitud)

print("\nMatriz de confusión:")
print(confusion_matrix(y_test, predicciones))

print("\nReporte de clasificación:")
print(classification_report(y_test, predicciones))

comparacion = pd.DataFrame({
    "Real": y_test.values,
    "Predicción": predicciones
})

print("\nComparación de resultados:")
print(comparacion)

nuevos_clientes = pd.DataFrame({
    "Compras_Mensuales": [1, 10, 18],
    "Gasto_Mensual_MXN": [500, 12000, 25000],
    "Visitas_Web_Mensuales": [2, 25, 50],
    "Satisfaccion": [2.5, 4.2, 5.0]
})

nuevos_clientes_escalados = escalador.transform(nuevos_clientes)

predicciones_nuevas = modelo.predict(nuevos_clientes_escalados)

print("\nPredicciones para nuevos clientes:")
print(predicciones_nuevas)

plt.plot(modelo.loss_curve_)
plt.xlabel("Iteraciones")
plt.ylabel("Error o pérdida")
plt.title("Proceso de aprendizaje de la red neuronal")
plt.show()

import pandas as pd
import numpy as np

np.random.seed(42)

n = 150

edad = np.random.randint(18, 66, n)
compras = np.random.randint(1, 21, n)
gasto = np.round(np.random.uniform(500, 25000, n), 2)
visitas = np.random.randint(1, 51, n)
satisfaccion = np.round(np.random.uniform(1, 5, n), 1)

puntaje = (
    gasto * 0.00008 +
    compras * 0.10 +
    visitas * 0.03 +
    satisfaccion * 0.20
)

nivel = []

for p in puntaje:
    if p < 1.8:
        nivel.append("bajo")
    elif p < 2.8:
        nivel.append("medio")
    else:
        nivel.append("alto")

df = pd.DataFrame({
    "ID_Cliente": [f"C{i:04d}" for i in range(1, n + 1)],
    "Edad": edad,
    "Compras_Mensuales": compras,
    "Gasto_Mensual_MXN": gasto,
    "Visitas_Web_Mensuales": visitas,
    "Satisfaccion": satisfaccion,
    "Nivel_Consumo_Referencia": nivel
})

df.to_csv("clientes (1).csv", index=False)

print("✅ Archivo clientes (1).csv creado correctamente")
print("Número de clientes:", len(df))
print(df.head())